name: Build Bare-Metal Artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Bare-Metal Rust Toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: thumbv7em-none-eabi

    - name: Run Cargo Check
      run: cargo check --target thumbv7em-none-eabi --verbose

    - name: Build Bare-Metal Binary
      run: cargo build --target thumbv7em-none-eabi --release --verbose

    - name: Upload Bare-Metal Artifact
      uses: actions/upload-artifact@v4
      with:
        name: volt-compiler-baremetal
        path: target/thumbv7em-none-eabi/release/volt_compiler
